# Task 1:
* create a function that accepts *argv. The first two arguments should be returned as one array, and the second two as another array.

In [ ]:
def first_task(*argv):
  return [argv[0:2], argv[2:4]]


In [ ]:
first_task(1, 4, 2, 3)

[(1, 4), (2, 3)]

In [ ]:
type(first_task(1, 4, 2, 3))

list

In [ ]:
def first_task_v2(*argv):
  return sum(argv[0:2]), sum(argv[2:4])

first_task_v2(1, 4, 2, 3)

(5, 5)

# Task 2:
* write a function that calculates n squares of numbers that takes only one argument
* e.g. second_task(4) returns \[0, 1, 4, 9]

In [ ]:
def squares(limit):
  r = 0
  ret = []

  while r < limit:
    ret.append(r**2)
    r += 1

  return ret

In [ ]:
squares(4)

[0, 1, 4, 9]

In [ ]:
for i in squares(4):
  print(i)

0
1
4
9


# Task 3:

* With the use of lambda expressions, pass onto a map a function for squaring all the elements of the list passed as the second arugment of the map
* display the result as list

In [ ]:
list(map(lambda x: x**2, [1, 2, 3, 4]))

[1, 4, 9, 16]

# Task 4

*   Create a lambda expression that will be used to filter the data less than or equal to 2 as value 0, and values greater than 2 should be treated as their current value
*   Show the results as a list



In [ ]:
list(map(lambda x: x if x > 2 else 0, [1, 2, 3, 4]))

[0, 0, 3, 4]

In [ ]:
list(filter(lambda x: x > 2, [1, 2, 3, 4]))

[3, 4]

In [ ]:
numbers = range(10)

In [ ]:
numbers

range(0, 10)

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
n = 2

In [ ]:
{n: n**2}

{2: 4}

In [ ]:
{n: 2 for n in numbers}

{0: 2, 1: 2, 2: 2, 3: 2, 4: 2, 5: 2, 6: 2, 7: 2, 8: 2, 9: 2}

In [ ]:
{n: n**2 for n in numbers if n % 2 == 0}

{0: 0, 2: 4, 4: 16, 6: 36, 8: 64}

# Task 5:

*   Create an array with numpy
*   Print the array
*   Check the ndim, shape, size, dtype, itemsize attributes
*   Generate special arrays like ones, zeroz, empty and arrays with random numbers (random, randint, linspace, arange)
*   Transform an array (reshape, eye)




In [ ]:
import numpy as np

In [ ]:
np.array([1, 2, 53])

array([ 1,  2, 53])

In [ ]:
np.array([(1.5, 2, 3), (4., 5., 6.)])

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
first_array = np.array([[1, 0, 3], [0, 1, 2]])
first_array

array([[1, 0, 3],
       [0, 1, 2]])

In [ ]:
first_array.ndim

2

In [ ]:
first_array.shape

(2, 3)

In [ ]:
first_array.size

6

In [ ]:
first_array.dtype

dtype('int64')

In [ ]:
first_array.itemsize

8

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones([3, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.empty([2, 2])

array([[1.94457641e-315, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [ ]:
np.random.random([2, 3])

array([[0.47871763, 0.79159681, 0.98505731],
       [0.33616664, 0.92739488, 0.7616552 ]])

In [ ]:
np.random.randint(5, size = (2, 4))

array([[1, 2, 1, 0],
       [2, 0, 4, 1]])

In [ ]:
np.linspace(0, 1, num = 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
np.linspace(0, 48, num = 7)

array([ 0.,  8., 16., 24., 32., 40., 48.])

In [ ]:
np.arange(0, 1, step = 0.3)

array([0. , 0.3, 0.6, 0.9])

In [ ]:
np.arange(120)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119])

In [ ]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
a, b

(array([20, 30, 40, 50]), array([0, 1, 2, 3]))

In [ ]:
a - b

array([20, 29, 38, 47])

In [ ]:
b**2

array([0, 1, 4, 9])

In [ ]:
a > 32

array([False, False,  True,  True])

In [ ]:
a += 1

In [ ]:
a

array([21, 31, 41, 51])

In [ ]:
a = np.random.random((2, 3))
a

array([[0.66314743, 0.4102344 , 0.95111418],
       [0.64694625, 0.33084287, 0.34254954]])

In [ ]:
a.sum()

np.float64(3.3448346738352805)

In [ ]:
a.min()

np.float64(0.33084286799190943)

In [ ]:
a.max()

np.float64(0.9511141804798492)

In [ ]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b.sum()

np.int64(66)

In [ ]:
b.sum(axis = 0)

array([12, 15, 18, 21])

In [ ]:
b.sum(axis = 1)

array([ 6, 22, 38])

In [ ]:
a = np.floor(10*np.random.random((3, 4)))

In [ ]:
a

array([[0., 6., 5., 3.],
       [7., 3., 9., 9.],
       [7., 0., 3., 5.]])

In [ ]:
a.transpose()

array([[0., 7., 7.],
       [6., 3., 0.],
       [5., 9., 3.],
       [3., 9., 5.]])

In [ ]:
b = a.ravel()
b

array([0., 6., 5., 3., 7., 3., 9., 9., 7., 0., 3., 5.])

In [ ]:
eye = np.eye(4)
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
from scipy import sparse

In [ ]:
sparse_matrix = sparse.csr_matrix(eye)
sparse_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (4, 4)>

In [ ]:
print("{}".format(sparse_matrix))

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (4, 4)>
  Coords	Values
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [ ]:
import pandas as pd

In [ ]:
pd.Series([1, 3, np.nan])

,0
0,1.0
1,3.0
2,NaN


In [ ]:
pd.Series([1, 3, 5], index = ['a', 'b', 'c'])

,0
a,1
b,3
c,5


In [ ]:
a = pd.Series({'a':1, 'b':2, 'c':3})

In [ ]:
a

,0
a,1
b,2
c,3


In [ ]:
a['a']

np.int64(1)

In [ ]:
a[['a', 'b']]

,0
a,1
b,2


In [ ]:
a[a > 1]

,0
b,2
c,3


In [ ]:
a * 2

,0
a,2
b,4
c,6


In [ ]:
np.sqrt(a)

,0
a,1.000000
b,1.414214
c,1.732051


In [ ]:
data = {'state': 'Serbia',
        'year': 2000,
        'population': 7}

In [ ]:
data

{'state': 'Serbia', 'year': 2000, 'population': 7}

# Task 6:

*  Create a dictionary that stores data of population in different countries
*  It should have state, year and population as its columns



In [ ]:
data = {'state': ['Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [200, 2001, 2001, 2002],
        'population': [1.5, 1.7, 2.4, 2.9]}

In [ ]:
data

{'state': ['Ohio', 'Ohio', 'Nevada', 'Nevada'],
 'year': [200, 2001, 2001, 2002],
 'population': [1.5, 1.7, 2.4, 2.9]}

In [ ]:
states = data['state']

In [ ]:
states

['Ohio', 'Ohio', 'Nevada', 'Nevada']

In [ ]:
states[2]

'Nevada'

In [ ]:
data['state'][2]

'Nevada'

In [ ]:
pd.DataFrame(data)

,state,year,population
0,Ohio,200,1.5
1,Ohio,2001,1.7
2,Nevada,2001,2.4
3,Nevada,2002,2.9


In [ ]:
pd.DataFrame(data, columns = ['state', 'year', 'color'])

,state,year,color
0,Ohio,200,NaN
1,Ohio,2001,NaN
2,Nevada,2001,NaN
3,Nevada,2002,NaN


# Task 7:


*   Load the dataset from the url and create a DataFrame and display it
*   https://raw.githubusercontent.com/hajdeger/AOP_PUB/master/datasets-uci-iris.csv



In [ ]:
url = 'https://raw.githubusercontent.com/hajdeger/AOP_PUB/master/datasets-uci-iris.csv'
df = pd.read_csv(url)
df

,5.1,3.5,1.4,0.2,Iris-setosa
0,4.9,3.0,1.4,0.2,Iris-setosa
1,4.7,3.2,1.3,0.2,Iris-setosa
2,4.6,3.1,1.5,0.2,Iris-setosa
3,5.0,3.6,1.4,0.2,Iris-setosa
4,5.4,3.9,1.7,0.4,Iris-setosa
...,...,...,...,...,...
144,6.7,3.0,5.2,2.3,Iris-virginica
145,6.3,2.5,5.0,1.9,Iris-virginica
146,6.5,3.0,5.2,2.0,Iris-virginica
147,6.2,3.4,5.4,2.3,Iris-virginica


In [ ]:
df = pd.read_csv('country_vaccinations.csv')
df

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Algeria,DZA,2021-01-29,0.0,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,Sputnik V,Ministry of Health,https://www.aps.dz/regions/116777-blida-covid-...
1,Algeria,DZA,2021-01-30,30.0,NaN,NaN,30.0,30.0,0.00,NaN,NaN,1.0,Sputnik V,Ministry of Health,https://www.aps.dz/regions/116777-blida-covid-...
2,Andorra,AND,2021-01-25,576.0,576.0,NaN,NaN,NaN,0.75,0.75,NaN,NaN,Pfizer/BioNTech,Government of Andorra,https://www.govern.ad/comunicats/item/12379-se...
3,Andorra,AND,2021-01-26,NaN,NaN,NaN,NaN,66.0,NaN,NaN,NaN,854.0,Pfizer/BioNTech,Government of Andorra,https://www.govern.ad/comunicats/item/12379-se...
4,Andorra,AND,2021-01-27,NaN,NaN,NaN,NaN,66.0,NaN,NaN,NaN,854.0,Pfizer/BioNTech,Government of Andorra,https://www.govern.ad/comunicats/item/12379-se...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2170,Wales,NaN,2021-01-29,378950.0,378200.0,750.0,15980.0,19705.0,12.02,12.00,0.02,6250.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
2171,Wales,NaN,2021-01-30,404249.0,403463.0,786.0,25299.0,19885.0,12.82,12.80,0.02,6307.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
2172,Wales,NaN,2021-01-31,417147.0,416306.0,841.0,12898.0,20824.0,13.23,13.20,0.03,6605.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
2173,Wales,NaN,2021-02-01,440706.0,439640.0,1066.0,23559.0,21508.0,13.98,13.94,0.03,6822.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...


# Task 8:

*   Print the indexes of the data
*   Print the column names
*   Print the values
*   Print the first 5 rows
*   Print the last 5 rows


In [ ]:
df.describe()

,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
count,1.437000e+03,1.128000e+03,6.220000e+02,1.168000e+03,2.097000e+03,1437.000000,1128.000000,622.000000,2097.000000
mean,9.601773e+05,9.961846e+05,2.266829e+05,6.172584e+04,5.015978e+04,3.815351,3.862332,0.899244,1777.146400
std,3.134587e+06,3.002411e+06,7.148116e+05,1.690664e+05,1.457979e+05,7.500090,6.711846,2.645650,3388.462636
min,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,2.116900e+04,2.631050e+04,4.537250e+03,1.798000e+03,1.358000e+03,0.360000,0.427500,0.050000,298.000000
50%,1.122130e+05,1.319230e+05,1.792900e+04,9.541500e+03,5.872000e+03,1.370000,1.580000,0.235000,797.000000
75%,4.951640e+05,5.676445e+05,1.077945e+05,5.032500e+04,2.462500e+04,3.240000,3.180000,0.757500,1431.000000
max,3.387825e+07,2.715496e+07,6.436931e+06,1.693241e+06,1.355451e+06,60.140000,38.800000,22.030000,30869.000000


In [ ]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,2165,2166,2167,2168,2169,2170,2171,2172,2173,2174
country,Algeria,Algeria,Andorra,Andorra,Andorra,Andorra,Andorra,Andorra,Andorra,Andorra,...,Wales,Wales,Wales,Wales,Wales,Wales,Wales,Wales,Wales,Wales
iso_code,DZA,DZA,AND,AND,AND,AND,AND,AND,AND,AND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
date,2021-01-29,2021-01-30,2021-01-25,2021-01-26,2021-01-27,2021-01-28,2021-01-29,2021-01-30,2021-01-31,2021-02-01,...,2021-01-24,2021-01-25,2021-01-26,2021-01-27,2021-01-28,2021-01-29,2021-01-30,2021-01-31,2021-02-01,2021-02-02
total_vaccinations,0.0,30.0,576.0,NaN,NaN,NaN,NaN,NaN,NaN,1036.0,...,271376.0,290147.0,312944.0,336745.0,362970.0,378950.0,404249.0,417147.0,440706.0,463657.0
people_vaccinated,NaN,NaN,576.0,NaN,NaN,NaN,NaN,NaN,NaN,1036.0,...,270833.0,289566.0,312305.0,336071.0,362253.0,378200.0,403463.0,416306.0,439640.0,462497.0
people_fully_vaccinated,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,543.0,581.0,639.0,674.0,717.0,750.0,786.0,841.0,1066.0,1160.0
daily_vaccinations_raw,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6322.0,18771.0,22797.0,23801.0,26225.0,15980.0,25299.0,12898.0,23559.0,22951.0
daily_vaccinations,NaN,30.0,NaN,66.0,66.0,66.0,66.0,66.0,66.0,66.0,...,17063.0,18279.0,19537.0,20845.0,21463.0,19705.0,19885.0,20824.0,21508.0,21530.0
total_vaccinations_per_hundred,0.0,0.0,0.75,NaN,NaN,NaN,NaN,NaN,NaN,1.34,...,8.61,9.2,9.93,10.68,11.51,12.02,12.82,13.23,13.98,14.71
people_vaccinated_per_hundred,NaN,NaN,0.75,NaN,NaN,NaN,NaN,NaN,NaN,1.34,...,8.59,9.18,9.91,10.66,11.49,12.0,12.8,13.2,13.94,14.67


In [ ]:
df.index

RangeIndex(start=0, stop=2175, step=1)

In [ ]:
df.columns

Index(['country', 'iso_code', 'date', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated',
       'daily_vaccinations_raw', 'daily_vaccinations',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'daily_vaccinations_per_million',
       'vaccines', 'source_name', 'source_website'],
      dtype='object')

In [ ]:
df.values

array([['Algeria', 'DZA', '2021-01-29', ..., 'Sputnik V',
        'Ministry of Health',
        'https://www.aps.dz/regions/116777-blida-covid-19-trente-vaccines-au-matin-du-1er-jour-de-la-campagne'],
       ['Algeria', 'DZA', '2021-01-30', ..., 'Sputnik V',
        'Ministry of Health',
        'https://www.aps.dz/regions/116777-blida-covid-19-trente-vaccines-au-matin-du-1er-jour-de-la-campagne'],
       ['Andorra', 'AND', '2021-01-25', ..., 'Pfizer/BioNTech',
        'Government of Andorra',
        'https://www.govern.ad/comunicats/item/12379-se-supera-el-miler-de-persones-vacunes-contra-el-coronavirus-sars-cov-2-a-andorra'],
       ...,
       ['Wales', nan, '2021-01-31', ...,
        'Oxford/AstraZeneca, Pfizer/BioNTech',
        'Government of the United Kingdom',
        'https://coronavirus.data.gov.uk/details/healthcare'],
       ['Wales', nan, '2021-02-01', ...,
        'Oxford/AstraZeneca, Pfizer/BioNTech',
        'Government of the United Kingdom',
        'https://coronav

In [ ]:
df.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Algeria,DZA,2021-01-29,0.0,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,Sputnik V,Ministry of Health,https://www.aps.dz/regions/116777-blida-covid-...
1,Algeria,DZA,2021-01-30,30.0,NaN,NaN,30.0,30.0,0.00,NaN,NaN,1.0,Sputnik V,Ministry of Health,https://www.aps.dz/regions/116777-blida-covid-...
2,Andorra,AND,2021-01-25,576.0,576.0,NaN,NaN,NaN,0.75,0.75,NaN,NaN,Pfizer/BioNTech,Government of Andorra,https://www.govern.ad/comunicats/item/12379-se...
3,Andorra,AND,2021-01-26,NaN,NaN,NaN,NaN,66.0,NaN,NaN,NaN,854.0,Pfizer/BioNTech,Government of Andorra,https://www.govern.ad/comunicats/item/12379-se...
4,Andorra,AND,2021-01-27,NaN,NaN,NaN,NaN,66.0,NaN,NaN,NaN,854.0,Pfizer/BioNTech,Government of Andorra,https://www.govern.ad/comunicats/item/12379-se...


In [ ]:
df.tail()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
2170,Wales,NaN,2021-01-29,378950.0,378200.0,750.0,15980.0,19705.0,12.02,12.00,0.02,6250.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
2171,Wales,NaN,2021-01-30,404249.0,403463.0,786.0,25299.0,19885.0,12.82,12.80,0.02,6307.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
2172,Wales,NaN,2021-01-31,417147.0,416306.0,841.0,12898.0,20824.0,13.23,13.20,0.03,6605.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
2173,Wales,NaN,2021-02-01,440706.0,439640.0,1066.0,23559.0,21508.0,13.98,13.94,0.03,6822.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
2174,Wales,NaN,2021-02-02,463657.0,462497.0,1160.0,22951.0,21530.0,14.71,14.67,0.04,6829.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...


# Task 9:



*   Sort indexes by axis 1 in the descending order



In [ ]:
df.sort_index(axis = 1, ascending = False)

,vaccines,total_vaccinations_per_hundred,total_vaccinations,source_website,source_name,people_vaccinated_per_hundred,people_vaccinated,people_fully_vaccinated_per_hundred,people_fully_vaccinated,iso_code,date,daily_vaccinations_raw,daily_vaccinations_per_million,daily_vaccinations,country
0,Sputnik V,0.00,0.0,https://www.aps.dz/regions/116777-blida-covid-...,Ministry of Health,NaN,NaN,NaN,NaN,DZA,2021-01-29,NaN,NaN,NaN,Algeria
1,Sputnik V,0.00,30.0,https://www.aps.dz/regions/116777-blida-covid-...,Ministry of Health,NaN,NaN,NaN,NaN,DZA,2021-01-30,30.0,1.0,30.0,Algeria
2,Pfizer/BioNTech,0.75,576.0,https://www.govern.ad/comunicats/item/12379-se...,Government of Andorra,0.75,576.0,NaN,NaN,AND,2021-01-25,NaN,NaN,NaN,Andorra
3,Pfizer/BioNTech,NaN,NaN,https://www.govern.ad/comunicats/item/12379-se...,Government of Andorra,NaN,NaN,NaN,NaN,AND,2021-01-26,NaN,854.0,66.0,Andorra
4,Pfizer/BioNTech,NaN,NaN,https://www.govern.ad/comunicats/item/12379-se...,Government of Andorra,NaN,NaN,NaN,NaN,AND,2021-01-27,NaN,854.0,66.0,Andorra
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2170,"Oxford/AstraZeneca, Pfizer/BioNTech",12.02,378950.0,https://coronavirus.data.gov.uk/details/health...,Government of the United Kingdom,12.00,378200.0,0.02,750.0,NaN,2021-01-29,15980.0,6250.0,19705.0,Wales
2171,"Oxford/AstraZeneca, Pfizer/BioNTech",12.82,404249.0,https://coronavirus.data.gov.uk/details/health...,Government of the United Kingdom,12.80,403463.0,0.02,786.0,NaN,2021-01-30,25299.0,6307.0,19885.0,Wales
2172,"Oxford/AstraZeneca, Pfizer/BioNTech",13.23,417147.0,https://coronavirus.data.gov.uk/details/health...,Government of the United Kingdom,13.20,416306.0,0.03,841.0,NaN,2021-01-31,12898.0,6605.0,20824.0,Wales
2173,"Oxford/AstraZeneca, Pfizer/BioNTech",13.98,440706.0,https://coronavirus.data.gov.uk/details/health...,Government of the United Kingdom,13.94,439640.0,0.03,1066.0,NaN,2021-02-01,23559.0,6822.0,21508.0,Wales


# Task 10:


*   Sort the data by values of total_vaccinations
*   Remove all the missing data



In [ ]:
df.sort_values(by = 'total_vaccinations').dropna()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
979,Isle of Man,IMN,2021-01-26,4886.0,4247.0,639.0,677.0,266.0,5.75,4.99,0.75,3128.0,Pfizer/BioNTech,Isle of Man Government,https://covid19.gov.im/general-information/cov...
980,Isle of Man,IMN,2021-01-27,5587.0,4550.0,1037.0,701.0,338.0,6.57,5.35,1.22,3975.0,Pfizer/BioNTech,Isle of Man Government,https://covid19.gov.im/general-information/cov...
981,Isle of Man,IMN,2021-01-28,6281.0,5243.0,1038.0,694.0,389.0,7.39,6.17,1.22,4575.0,Pfizer/BioNTech,Isle of Man Government,https://covid19.gov.im/general-information/cov...
982,Isle of Man,IMN,2021-01-29,6859.0,5829.0,1030.0,578.0,459.0,8.07,6.86,1.21,5398.0,Pfizer/BioNTech,Isle of Man Government,https://covid19.gov.im/general-information/cov...
1209,Luxembourg,LUX,2021-01-26,9525.0,8280.0,1245.0,971.0,604.0,1.52,1.32,0.20,965.0,Pfizer/BioNTech,Government of Luxembourg,https://data.public.lu/fr/datasets/r/fec6d5ff-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2118,United States,USA,2021-01-30,29577902.0,24064165.0,5259693.0,1693241.0,1291416.0,8.84,7.20,1.57,3861.0,"Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://covid.cdc.gov/covid-data-tracker/#vacc...
2119,United States,USA,2021-01-31,31123299.0,25201143.0,5657142.0,1545397.0,1324949.0,9.31,7.54,1.69,3962.0,"Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://covid.cdc.gov/covid-data-tracker/#vacc...
2120,United States,USA,2021-02-01,32222402.0,26023153.0,5927847.0,1099103.0,1355451.0,9.63,7.78,1.77,4053.0,"Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://covid.cdc.gov/covid-data-tracker/#vacc...
2121,United States,USA,2021-02-02,32780860.0,26440836.0,6064792.0,558458.0,1319981.0,9.80,7.91,1.81,3947.0,"Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://covid.cdc.gov/covid-data-tracker/#vacc...
